theme = "semi-native"
icons = "awesome"

[[block]]
block = "net"
interval = 60

[[block]]
block = "disk_space"
path = "/"
format = "{icon} {percentage}"
info_type = "available"
unit = "GB"
alert_absolute = true
warning = 20
alert = 10

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

# Uncomment below to enable battery
[[block]]
block = "battery"
interval = 180
format = " {percentage}"
full_format = " {percentage}"
hide_missing = true
driver = "sysfs"

[[block]]
block = "rofication"
interval = 5
socket_path = "/tmp/rofi_notification_daemon"

[[block]]
block = "net"
interval = 60
format = ""  # Don't display activity; too distracting

[[block]]
block = "sound"
driver = "pulseaudio"

[[block]]
block = "time"
interval = 5
format = "%a %Y-%m-%d %H:%M"

